### ISSUE TITLE
Bug in the z-axis index calculations in surf2volz.m

### ISSUE THREAD

**Issue by MartinKjer** [fangq/iso2mesh#10]
Shouldn't line 57 surf2volz.m read:
zz=floor(((zi(iz(i))-zi(1)))/dz0);

I just had some cases where the generated volume grew larger in the z-dim than the input vector specified. It created some issues with the calls in surf2vol.m.

**Comment by fangq** [comment]
good catch! the reported bug is now fixed in SVN rev#494

http://sourceforge.net/p/iso2mesh/code/494/

feel free to close the bug if this works for you. thanks for reporting!
