### ISSUE TITLE
cgal* tools does not compile

### ISSUE THREAD

**Issue by ignatenkobrain** [fangq/iso2mesh#12]
I downloaded repo from sourceforge and trying to build cgal\* tools from source because we are not allowed to put already compiled binaries to packages in Fedora:
# cgalsurf

```
[brain@x1carbon build]$ make -j4
Scanning dependencies of target mesh_a_3d_gray_image
[ 50%] Building CXX object CMakeFiles/mesh_a_3d_gray_image.dir/mesh_a_3d_gray_image.cpp.o
/home/brain/rpmbuild/BUILD/iso2mesh-code-502-trunk/cgalsurf/mesh_a_3d_gray_image.cpp: In function ‘int main(int, char**)’:
/home/brain/rpmbuild/BUILD/iso2mesh-code-502-trunk/cgalsurf/mesh_a_3d_gray_image.cpp:76:95: error: no matching function for call to ‘make_surface_mesh(C2t3&, Surface_3&, CGAL::Surface_mesh_default_criteria_3<CGAL::Delaunay_triangulation_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_data_structure_3<CGAL::Surface_mesh_vertex_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_vertex_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Surface_mesh_cell_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_cell_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_cell_base_3<void> > > >, CGAL::Sequential_tag>, CGAL::Default, CGAL::Default> >&, CGAL::Manifold_tag, unsigned int&, int)’
   CGAL::make_surface_mesh(c2t3, surface, criteria, CGAL::Manifold_tag(),initnum,atoi(argv[10]));
                                                                                               ^
In file included from /home/brain/rpmbuild/BUILD/iso2mesh-code-502-trunk/cgalsurf/mesh_a_3d_gray_image.cpp:6:0:
/usr/include/CGAL/make_surface_mesh.h:47:6: note: candidate: template<class C2T3, class Surface, class Criteria, class Tag> void CGAL::make_surface_mesh(C2T3&, const Surface&, const Criteria&, Tag, int)
 void make_surface_mesh(C2T3& c2t3,
      ^
/usr/include/CGAL/make_surface_mesh.h:47:6: note:   template argument deduction/substitution failed:
/home/brain/rpmbuild/BUILD/iso2mesh-code-502-trunk/cgalsurf/mesh_a_3d_gray_image.cpp:76:95: note:   candidate expects 5 arguments, 6 provided
   CGAL::make_surface_mesh(c2t3, surface, criteria, CGAL::Manifold_tag(),initnum,atoi(argv[10]));
                                                                                               ^
In file included from /home/brain/rpmbuild/BUILD/iso2mesh-code-502-trunk/cgalsurf/mesh_a_3d_gray_image.cpp:6:0:
/usr/include/CGAL/make_surface_mesh.h:64:6: note: candidate: template<class C2T3, class SurfaceMeshTraits_3, class Criteria, class Tag> void CGAL::make_surface_mesh(C2T3&, const typename SurfaceMeshTraits_3::Surface_3&, const SurfaceMeshTraits_3&, const Criteria&, Tag, int)
 void make_surface_mesh(C2T3& c2t3,
      ^
/usr/include/CGAL/make_surface_mesh.h:64:6: note:   template argument deduction/substitution failed:
/usr/include/CGAL/make_surface_mesh.h: In substitution of ‘template<class C2T3, class SurfaceMeshTraits_3, class Criteria, class Tag> void CGAL::make_surface_mesh(C2T3&, const typename SurfaceMeshTraits_3::Surface_3&, const SurfaceMeshTraits_3&, const Criteria&, Tag, int) [with C2T3 = CGAL::Complex_2_in_triangulation_3<CGAL::Delaunay_triangulation_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_data_structure_3<CGAL::Surface_mesh_vertex_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_vertex_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Surface_mesh_cell_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_cell_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_cell_base_3<void> > > >, CGAL::Sequential_tag>, CGAL::Default, CGAL::Default> >; SurfaceMeshTraits_3 = CGAL::Surface_mesh_default_criteria_3<CGAL::Delaunay_triangulation_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_data_structure_3<CGAL::Surface_mesh_vertex_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_vertex_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Surface_mesh_cell_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_cell_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_cell_base_3<void> > > >, CGAL::Sequential_tag>, CGAL::Default, CGAL::Default> >; Criteria = CGAL::Manifold_tag; Tag = unsigned int]’:
/home/brain/rpmbuild/BUILD/iso2mesh-code-502-trunk/cgalsurf/mesh_a_3d_gray_image.cpp:76:95:   required from here
/usr/include/CGAL/make_surface_mesh.h:64:6: error: no type named ‘Surface_3’ in ‘class CGAL::Surface_mesh_default_criteria_3<CGAL::Delaunay_triangulation_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_data_structure_3<CGAL::Surface_mesh_vertex_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_vertex_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_vertex_base_3<void> > >, CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Surface_mesh_cell_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_cell_base_3<CGAL::Robust_circumcenter_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_cell_base_3<void> > > >, CGAL::Sequential_tag>, CGAL::Default, CGAL::Default> >’
CMakeFiles/mesh_a_3d_gray_image.dir/build.make:62: recipe for target 'CMakeFiles/mesh_a_3d_gray_image.dir/mesh_a_3d_gray_image.cpp.o' failed
make[2]: *** [CMakeFiles/mesh_a_3d_gray_image.dir/mesh_a_3d_gray_image.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mesh_a_3d_gray_image.dir/all' failed
make[1]: *** [CMakeFiles/mesh_a_3d_gray_image.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

And for `cgalsimp2` and `cgalmesh` I dont understand how to compile it to one binary which will be used by iso2mesh.

**Comment by fangq** [comment]
@ignatenkobrain 

both cgalsurf and cgalmesh utilities were compiled using a customized older version of CGAL (3.8). 

for cgalsurf, you need to download CGAL 3.8, copy the files under cgalsurf/CGAL and cgalmesh/CGAL/ to CGAL-3.8/include/CGAL and overwrite the original files. Then build CGAL library using the following command

```cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=FALSE -DMPFR_LIBRARIES=/usr/lib/x86_64-linux-gnu/libmpfr.a -DMPFR_INCLUDE_DIR=/usr/include \
-DGMP_LIBRARIES="/usr/lib/x86_64-linux-gnu/libgmp.a" -DGMPXX_LIBRARIES=/usr/lib/x86_64-linux-gnu/libgmpxx.a -DMPFR_LIBRARY_DIR=/usr/lib \
-DGMP_LIBRARY_DIR=/usr/lib -DGMP_INCLUDE_DIR=/usr/include -DOPENGL_INCLUDE_DIR=/usr/X11R6/include \
-DWITH_examples=true -DCGAL_CXX_FLAGS="-I/usr/include -L/usr/lib" -DBoost_LIBRARYDIR=/usr/lib \
-DBoost_LIBRARIES=/usr/lib/libboost_thread.a  
```

if some of the libraries have not been installed, install them first. once libCGAL*.a were compiled, go to CGAL-3.8/examples/, copy cgalsurf/*.cpp to examples/Surface_mesher/, and cgalmesh/*.cpp to examples/Mesh_3, then cd each folder, type "make" or "make copied_target_file.cpp".

similar for cgalsimp2.

**Comment by ignatenkobrain** [comment]
I dont want to download old CGAL, build it and so on. I'm working on packaging iso2mesh and it's not allowed to bundle any deps

**Comment by fangq** [comment]
@ignatenkobrain 

which Linux distribution are you packing iso2mesh for? I know rules vary from distribution to distribution, can you package the executables under iso2mesh/bin/* as no-arch binary data for now (and chmod +x in post_installation script)? all of them are statically linked executables and do not require additional libraries to run.

**Comment by ignatenkobrain** [comment]
Fedora. No, I can't .

**Comment by fangq** [comment]
Maybe a temporary solution is to package the .m files only. Users will be able to use all (but limited) features that do not depend on the binaries. When the binaries are invoked, we can prompt the users to download the binaries separately.

**Comment by ignatenkobrain** [comment]
Will you in the future make available to build that programs using system cgal?

**Comment by fangq** [comment]
yes I will. However, CGAL and tetgen have many updates over the past years. Their algorithms were changed, resulting in different meshes. The strategies for upgrading the binaries have to be carefully considered.

Nonetheless, I committed the following update to iso2mesh

**Comment by fangq** [comment]
alright, I have a better solution, see this patch

https://github.com/fangq/iso2mesh/commit/fcad5c86f76b63f496f5bc4dbcebd2ffe11c5c6c

iso2mesh now can automatically download the binary when missing. When you package, just to make sure you have an empty bin folder under iso2mesh. Otherwise, the mcpath script will not be able to get the correct full path.

let me know if this works for you.

**Comment by ignatenkobrain** [comment]
I will need to kick this patch out. Such things is prohibited.

**Comment by fangq** [comment]
why it is prohibited? I don't understand. nothing violates the license here. GPL codes allow communications with modules of other license forms via pipes. This is called "mere aggregation".

see http://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#MereAggregation

if will be impossible to put together any Linux distributions if such communication is prohibited. Not mention that the modules iso2mesh tries to communicate is under open-source license.

**Comment by mhough** [comment]
Hi Qianqian, thanks for your time on this. Just so you know we have fedora packaging requirements we have to follow that aren't just a question of the licensing but include issues such as external bundling and building the entire package from source that I am still learning about myself. Hopefully we can still work something out. 

On a related but separable note, I would be interested to know how you would compare the output of iso2mesh+CGAL 3.8 vs iso2mesh+CGAL 4.7 (or whatever the system version is at this point)? What issues would you be concerned about? Happy to follow up with you about this on the mailing list.

**Comment by fangq** [comment]
@mhough thanks for the comment. I had been a Fedora package maintainer for a couple of years myself (5 years back). I was aware of the packaging guidelines and review process.

Checking out the latest packaging guidelines, I believe you were talking about this

https://fedoraproject.org/wiki/Packaging:Guidelines#Packages_which_are_not_useful_without_external_bits

I am certainly happy to work with you guys and figure out a solution, at this point, my justifications to package iso2mesh as is are the following

first, iso2mesh contains a rich set of mesh processing functions; only 12 out of  130 .m files requires external files. To the minimum, giving users access to those independent .m functions is going to be helpful.

second,  the guideline prohibits bundling with "non-free, legally unacceptable, or binary-only", this is not the case for iso2mesh. All included binaries in iso2mesh are free-software, without legal/licensing issues, and all have publicly available source code (except tetgen 1.4, which is potentially a non-free license - no-commercial use, but tetgen 1.5 was re-licensed to AGPLv3, which is also included in iso2mesh). Just remove tetgen 1.4 and rename all tetgen1.5.* to tetgen.* in your packaging script. 

thirdly, the toolbox itself is in the .m format, which is in the source code form by nature. for the binaries in the bin folder, you CAN indeed build all of them from the source (for Tetgen, you can build from tetgen 1.5 source). The only issue is the fact that a subset of the binaries (cgal*) requires a patched CGAL library. Maybe we can submit this patched CGAL library as a separate package as a dependency.

Regarding your question for iso2mesh+CGAL 3.x vs 4.x, here is a bug tracker for one of the CGAL issues as an example

https://github.com/fangq/iso2mesh/issues/4

in the older CGAL with my RNG patch, at least the node list is reproducible, but in the new CGAL, node list varies every time.

**Comment by fangq** [comment]
I reverted the auto-download feature, just to be more friendly with the guidelines. I also added fall-backs to system-wide-installed binaries (for now, just tetgen) - when tetgen under bin/ is missing, I will check if the system has tetgen installed (many Linux distros have tetgen as a separate package).

here are my changes

https://github.com/fangq/iso2mesh/commit/ba7fc4322e68ffda0bdc9f2f6be56988c078eb7c
https://github.com/fangq/iso2mesh/commit/75724b53aca2d433295c63ace3eaf7a2cbd415a8

this should solve the dependency to tetgen. 

The remaining binaries include 3 CGAL tools (requires a modified libCGAL), 1 libGTS tool (libgts/examples/set unmodified, http://gts.sf.net/), 1 Jmesh tool (JMeshLib test code unmodified, http://jmeshlib.sf.net/) and 1 meshfix utility (https://code.google.com/p/meshfix/ unmodified). Most of these should be readily compilable except for the CGAL tools.

**Comment by fangq** [comment]
@ignatenkobrain and @mhough, I added the customized CGAL utility source files (for cgalmesh, cgalsurf and cgalsimp2) as well as other needed tools (meshfix, cork). I also added makefiles to compile these source codes to binaries, see

https://github.com/fangq/iso2mesh/commit/17bf732b2a90e923b5390d95af2b8c23558e572d
https://github.com/fangq/iso2mesh/commit/8d015f4decf002a5fc9591e74690c3f5cd8fcd6f

now, one can download iso2mesh, delete all binaries in the bin folder, and use the recompiled binaries instead.

To give it a try, here are the commands 

```
git clone --recurse-submodules https://github.com/fangq/iso2mesh.git
cd iso2mesh
rm -rf bin/*.mex* bin/*.exe
cd tools
make
```
the above commands should recreate most of the utilities needed by iso2mesh in bin/

on the Ubuntu 14.04 machine that I tested, the dependency of the compilation/execution include

1. libcgal-dev
2. clang
3. cmake
4. superlu (maybe)

in addition, I did not checkout/compile for tetgen, so I assume users have already installed tetgen via package management tools (dnf, apt-get ...)

if you happen to revisit packaging iso2mesh, please let me know if the above changes are helpful.

thanks

**Comment by fangq** [comment]
closing this tracker after releasing iso2mesh 1.9

**Comment by lrineau** [comment]
Hi @fangq @ignatenkobrain @mhough, I read in this discussion that the binaries of iso2mesh using CGAL are compiled using 3.8. I would like to work with you on adapting the code to CGAL version 4.13 (and later).
