### ISSUE TITLE
Connect Objecct Mesh 

### ISSUE THREAD

**Issue by qiujian3328103** [fangq/iso2mesh#14]
Does iso2mesh have a function to mesh two connected objects? I recently created a model that contains several overlapping ellipsoids. I used the triangular element to mesh the surface of each ellipsoid. However, when I tried to use the surf2mesh function create a 3d tetrahedral elements the function doesn't work. I believe the reason is that some of the nodes on one ellipsoid in inside another ellipsoid. How can I deal with this problem?

**Comment by fangq** [comment]
you need to use the surfboolean function to combine all surfaces

https://github.com/fangq/iso2mesh/blob/master/surfboolean.m
