### ISSUE TITLE
cgal binaries do not produce output files

### ISSUE THREAD

**Issue by JoshBrownNeuro** [fangq/iso2mesh#16]
I've found in issue in which the cgalsim2 and cgalsurf binaries fail to generate output files.  I've replicated this on my RHEL5, RHEL7, and Windows 10 64-bit machines.  The binaries take the input files such as pre_remesh.off, but they fail to produce the output files.  I checked, and the temp directory is writable, and the binaries are getting the full paths for input and output files.  (I would attach the input files, but they are 19 MB).  I can't find a workaround here.  The binaries run with no apparent errors but don't generate output files, like so:

Finished...
547842 edges removed.
6 final edges.
<matlab debug, then continue>
47    [node,elem]=readoff(mwpath('post_remesh.off'));
Error using fgets
Invalid file identifier.

Would love to use this software!  Thanks.

**Comment by JoshBrownNeuro** [comment]
OK the error was not a bug -- the problem was that I neglected to specify the options in the v2m call.  That led to empty arguments to the binaries, hence the failure to generate output.  I think a simple check in the matlab code as to whether the "opt" argument is empty would prevent this issue in the future.

**Comment by fangq** [comment]
thanks, I agree that an error should be given when no argument is supplied (or default values should be set).
