### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by bspatter** [fangq/iso2mesh#23]
node output of vol2mesh is sometimes an Nx4 matrix when handed a 3D logical array. This is not consistent with the node dimensions in the input to savemsh.m, savestl.m, etc...

Saving only the first three columns seems to work to fix this.

**Comment by fangq** [comment]
if you call vol2mesh with method='cgalmesh', the cgalmesher outputs a Nx4 array with the 4th column node labels (for the regions it belongs to). For other methods, the output is typically Nx3. Although the cgalmesher node label in most cases is not useful, but I kept this output format just in case, and rely on users to trim it  (node(:,1:3)) if such column is not supported (such as meshconn, volface, elemvolume, savemsh, ...).

Please use node(:,1:3) for further processing of such output. In the future, I plan to fundamentally address this issue using the JMesh specification, if I can really find time to finish it

http://iso2mesh.sourceforge.net/cgi-bin/index.cgi?jsonlab/Doc/JMesh
