### ISSUE TITLE
Possible bug in vol2surf

### ISSUE THREAD

**Issue by FedeArtico** [fangq/iso2mesh#25]
When generating a mesh from image slices, Matlab shows this error "Operands to the || and && operators must be convertible to logical scalar values." at the line 87 of vol2surf.m. I think it is related to the fact that it is a matrix comparison so & should be used instead of &&. After changing that it seems to work fine, but you may want to check it just in case.

**Comment by fangq** [comment]
this issue should have been fixed about 7 months ago in this commit

https://github.com/fangq/iso2mesh/commit/11438d1d5ce5e2abf35f1e4eed2a412c6e57c128

please checkout the latest github version and let me know if this is still an issue. Closing for now, but feel free to reopen if the problem remains.
