### ISSUE TITLE
iso2mesh in Lead DBS

### ISSUE THREAD

**Issue by ariannafelice** [fangq/iso2mesh#27]
Dear all,
i'm using iso2mesh inside the toolbox Lead DBS and i would like to calculate the VTA. I need to know if in the mesh we consider the anisotropy and the inhomogeneity of the surrounding tissues to the nuclei. 
Can someone give me some explanation about this?
Thank you in advance for your collaboration.
Regards,
Arianna

**Comment by fangq** [comment]
can you explain what you meant by "anisotropy and inhomogeneity" of the tissues? do you want to add additional objects/surfaces when processing the electrode mesh?
