### ISSUE TITLE
How to find indices of nodes to faces

### ISSUE THREAD

**Issue by NataCalc** [fangq/iso2mesh#28]
Hello,

I am projecting the pointCloud (vertices2) to surface (vertices1, faces1) using proj2mesh:
1) calculate the nodal norm
nv=nodesurfnorm(vertices1,faces1);
2) calculate the distances
[d2surf,cnL]=dist2surf(vertices1,nv,vertices2);
3) project 
[newptL elemidL weightL]=proj2mesh(vertices1,faces1,vertices2,nv,cnL);

elemidL corresponds to surface triangle (in elem) containing projected point? if so, I do have faces1(elemidL,:). How to find corresponding vertices1 IDs of these triangles to form the surface which contains all projected points? 

how to get nodes order from element id?

Regards

**Comment by fangq** [comment]
@NataCalc, the indices of the 3 nodes forming faces1(elemidL(1),:) is exactly that:

`faces1(elemidL(1),:) 
`
or did I misunderstood your question?

**Comment by NataCalc** [comment]
What would be index for vertices1(ID,:)? What is ID for vertices if I know elemID?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by fangq** [comment]
it is just linear index, ID=1 means the first node, 2, the 2nd node, etc.

**Comment by NataCalc** [comment]
Thanks, figured it out.

Another question, I have to export surface with corresponding vertices ID/faces ID (corresponding to trignles containing projected points). When I do this ordinary way and re-load surface, ID do not correspond anymore to interested faces/vertices. Do you know the way to labal these ID(color or something) and export in STL?

Thanks in advance

**Comment by fangq** [comment]
@NataCalc, sorry for the delay. I took a quick look at the savestl.m function in iso2mesh, I don't think it supports exporting labels/colors to stl. Looks like color is only supported in non-standard binary stls

https://en.wikipedia.org/wiki/STL_(file_format)#Color_in_binary_STL

can you let me know what type of data you want to export in stl?
