### ISSUE TITLE
v2m parameter "isovalues"

### ISSUE THREAD

**Issue by artturuohola** [fangq/iso2mesh#31]
isovalues: a list of isovalues where the levelset is defined

Is there another way to explain what this parameter is, I don't understand it.

**Comment by fangq** [comment]
do you want to suggest something? it seems clear to me, despite brief.

**Comment by artturuohola** [comment]
Okay, Hmm I have a volumetric image consisting of grayscale colors 64 and 128, the shape is a sphere of radius 200, centrer at (250,250,250). What would the isovalues be in this case?

Thank you

**Comment by fangq** [comment]
@artturuohola, any value between 64 and 128 will give you the boundary between the two regions. there is a linear interpolation between the adjacent voxel, so, choosing different value will produce a very slightly different surface. If there is no particular reason, I typically choose the middle point (64+128)/2=96

**Comment by artturuohola** [comment]
Thank you, what value would you choose in the case of a head volume, consisting of air, bone, skin, csf, gray and white matter, defined by colors 42.5000   85.0000  127.5000  170.0000  212.5000  255.0000?

**Comment by fangq** [comment]
@artturuohola, you won't be able to use v2m to create a multi-label mesh using isosurfaces (unless you  volume is a gray-scale image with each level-set completely separate from another one.

you should consider setting isovalues to [] and set method to 'cgalmesh'.
