### ISSUE TITLE
Index exceeds the number of array elements (0).

### ISSUE THREAD

**Issue by praveenvenky** [fangq/iso2mesh#33]
hello,

Please help me solving error for my following code:
[node11,elem11,face11] = s2m(node1,face1,keepratio,maxvol)

The error is as follows:

Index exceeds the number of array elements (0).

Error in savesurfpoly (line 104)
    boxnode=[p0;p1(1),p0(2:3);p1(1:2),p0(3);p0(1),p1(2),p0(3);

Error in surf2mesh (line 88)
savesurfpoly(no,el,holes,regions,p0,p1,mwpath('post_vmesh.poly'),dobbx);

Error in s2m (line 40)
    [node,elem,face]=surf2mesh(v,f,[],[],keepratio,maxvol,regions,holes);

Error in main1 (line 215)
  [node11,elem11,face11] = s2m(node1,face1,keepratio,maxvol)

Thanks in advance. 
Best Regards

**Comment by fangq** [comment]
please post a sample script/data, so I can reproduce the error. otherwise it is difficulty to comment.
