### ISSUE TITLE
Compilation seems broken in Ubuntu 18.10

### ISSUE THREAD

**Issue by Aabaz** [fangq/iso2mesh#39]
Hello,
compilation seems broken in Ubuntu 18.10.

Running make on tag v1.9.1 fails with error:
```
~/iso2mesh/tools/meshfix/contrib/OpenNL3.2.1/src/nl_single_file.c:3439:10: fatal error: SuperLU/slu_cdefs.h: No such file or directory
 #include <SuperLU/slu_cdefs.h>
          ^~~~~~~~~~~~~~~~~~~~~
```

It works fine if I revert commit 24736f5 which makes sense since this commit (updating the meshfix submodule to commit cc7430c) added the "SuperLU" directory in the include which does not exist in Ubuntu (at least not in my setup).

Maybe there is a configuration option to specify the include directory for SuperLU that I missed.

Additional info:
- Linux distribution: Ubuntu 18.10 Cosmic
- SuperLU package: libsuperlu-dev:amd64 version 5.2.1+dfsg1-3build1
- SuperLu include directory: /usr/include/superlu

Hope this helps.

Best regards,

**Comment by fangq** [comment]
this should now be fixed.
