### ISSUE TITLE
Convert PointCloud to triangulation mesh

### ISSUE THREAD

**Issue by uredavid** [fangq/iso2mesh#44]
Hi, 

I need to convert point cloud to triangulation mesh with Matlab. I have a 3D matrix (x,y,z coordinates) and I need a triangulation mesh matrix with the vertices of each triangle to calculate the curvature of each of them.

It is possible to do it with iso2mesh??

Thank you!

**Comment by fangq** [comment]
hi @uredavid, it is on the roadmap for the future releases, but currently, we haven't integrated these features. however, I've tried calling the PoissonRecon executable from the below URL:

http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version12.00/
https://github.com/mkazhdan/PoissonRecon

and was able to obtain reasonable surfaces. If the surface is open, I also need to call meshcheckrepair('meshfix') to close the surface.

give it a try. I will close this ticket for now, but will consider adding this in the future.
