### ISSUE TITLE
surf2mesh/Tetgen v1.9.2: Different behavior with MacOS?

### ISSUE THREAD

**Issue by ftadel** [fangq/iso2mesh#48]
A Brainstorm user reported an issue with MacOS here:
https://neuroimage.usc.edu/forums/t/fem-meshing-and-fem-head-model/18920/6

Yvonne prepared an example dataset which works well on Windows 10 and Ubuntu 18, but fails on her MacOS computer (surf2mesh: Tetgen command failed).

More precisely:
- it fails with iso2mesh version 1.9.2 (https://github.com/fangq/iso2mesh/releases/download/v1.9.2/iso2mesh-1.9.2-osx64.zip)
- it seems to work (or at lease iso2mesh doesn't crash) with the current version from this repository (then there is an error on the Brainstorm side that I need to investigate further).

Is there anything that could explain this behavior?
Something that was fixed for MacOS after you released v1.9.2?

**Comment by fangq** [comment]
hi @ftadel, I don't have issue running this sample on my mac with either the latest master branch or the v1.9.2 version. see screenshot at the bottom.

from the original bug report, it does seem to be clear whether there was an iso2mesh or tetgen error. if you have more input on this, please let me know.

![mac_os_iso2mesh](https://user-images.githubusercontent.com/226913/82056409-ee41c980-968f-11ea-8ed9-c317b3de2d63.png)

**Comment by yvonnebuschermoehle** [comment]
Hey @ftadel and @fangq, 

I am not sure how to exactly reproduce the above computations, but I am trying to answer all the questions that have come up: 

@ftadel, what I mean by "it's not properly installed" is, that I get the error, that it could not be installed, but the iso2mesh folder is being created within the .brainstorm folder. I can then use it to create a mesh, but it crashes in the following way:

![Bildschirmfoto 2020-05-15 um 16 14 07](https://user-images.githubusercontent.com/65216578/82060350-90c96f00-96c7-11ea-9cda-c025c5f521e2.png)

When I use the manually downloaded version, I can compute a mesh, but when I try to display it, I get the following: 

![Bildschirmfoto 2020-05-15 um 16 15 28](https://user-images.githubusercontent.com/65216578/82060411-a8085c80-96c7-11ea-917c-055a63d8103d.png)

On Windows, I was able to reproduce the results that Francois uploaded in the brainstorm forum. 

I hope that helps!

**Comment by yvonnebuschermoehle** [comment]
Just found dropbox link to reproduce what @fangq posted, I'm on it!

**Comment by yvonnebuschermoehle** [comment]
Here the results: 

first try with the preinstalled version, second try with the manually dowloaded version added to my path. 
![Bildschirmfoto 2020-05-15 um 16 36 22](https://user-images.githubusercontent.com/65216578/82062399-57463300-96ca-11ea-9f01-73c4e6c9b789.png)

**Comment by ftadel** [comment]
Can execute the following, after removing all the iso2mesh folders from the Matlab path, and the iso2mesh folder from the .brainstorm folder:
```
process_generate_fem('InstallIso2mesh', 1)
addpath /Users/yvonnebuschermohle/.brainstorm/iso2mesh/mac64/iso2mesh
```
Then repeat the previous test. 
The iso2mesh folder was not in your path...

**Comment by yvonnebuschermoehle** [comment]
then I find this: 

![Bildschirmfoto 2020-05-15 um 16 48 33](https://user-images.githubusercontent.com/65216578/82063639-03d4e480-96cc-11ea-9ff1-e70ffc6c2a93.png)

**Comment by ftadel** [comment]
With Brainstorm running...

**Comment by yvonnebuschermoehle** [comment]
Sure, sorry!

![Bildschirmfoto 2020-05-15 um 16 48 33](https://user-images.githubusercontent.com/65216578/82064360-f53afd00-96cc-11ea-85de-661cc40b4836.png)

**Comment by yvonnebuschermoehle** [comment]
Sure, sorry! 

![Bildschirmfoto 2020-05-15 um 16 56 51](https://user-images.githubusercontent.com/65216578/82064478-1d2a6080-96cd-11ea-9c5a-e7095f465b02.png)

**Comment by ftadel** [comment]
@fangq Here we have the reproduction of the bug, finally.
Sorry for all this pollution on your github repo :)
Any suggestion?

**Comment by fangq** [comment]
@yvonnebuschermoehle, ok, now I can see this is triggered by a failed tetgen session.

can you do the following

first, in matlab, type `mwpath`, and it should print something like `/private/tmp/iso2mesh-youraccount`, also type `mcpath(['tetgen.' mexext])`, this will print the path to the tetgen binary.

now, open a terminal, cd the path as mwpath printed, and then run
```
/path/to/tetgen.mexmaci64  post_vmesh.poly
```

and see if you can find any additional error messages. if this fails, please also try
```
/path/to/tetgen1.5.mexmaci64  post_vmesh.poly
```

and see if the tetgen1.5 binary also fails. 

Overall, tetgen (1.4.3) has been quite robust overall, but we have seen situations like this if the input surface contains non-manifold nodes (and other borderline cases). We noticed that tegen 1.5 works form some of these failed cases, but fails on some other cases where 1.4.3 worked; also, tetgen 1.5's output does not reproduce what 1.4.3 outputs, so I was reluctant to change default to 1.5, but provided both in case one fails.

please let me know what you see.

**Comment by yvonnebuschermoehle** [comment]
Thanks, @fangq, 
here is what I reproduced (I really hope I did everything correct). For the tetgen1.5 at least some results are shown here. 

![Bildschirmfoto 2020-05-15 um 17 54 55](https://user-images.githubusercontent.com/65216578/82070758-7d250500-96d5-11ea-9028-21133131ac35.png)

**Comment by fangq** [comment]
now I realized that on a mac, `tetgen.mexmaci64` is a link pointing to tetgen1.5.mexmaci64 in the `iso2mesh/bin` folder.

from your screenshot, it looks tetgen 1.5 worked fine with the input, but when you run the command using tetgen (as a link) it failed to find the tetgen1.5 in the same folder? was there a typo?

if your tetgen 1.5 command works, you may set the `method` option in your `surf2mesh` call to `tetgen1.5` and rerun the command. this should call tetgen1.5 directly (calling method=tetgen should have also worked if the link worked ok).

**Comment by yvonnebuschermoehle** [comment]
@fangq It was not a typo and the x flags were also fine, the link really does not seem to work in the manually downloaded version. In the master version it's not a problem and both tetgens work. As proposed, I changed the method in surf2mesh to tetgen1.5 and now I can generate the mesh. Another possibility I tried is to replace the tetgen.mexmaci64 file with the same one from the master toolbox, that works aswell!
Thanks a lot for your help!

**Comment by fangq** [comment]
@yvonnebuschermoehle, I just downloaded the [iso2mesh-1.9.2-osx64.zip](https://github.com/fangq/iso2mesh/releases/download/v1.9.2/iso2mesh-1.9.2-osx64.zip) file and manually extract (call unzip in a terminal) and addpath to matlab, it also works in my versions of matlab and osx. 

what unzipping method did you use? can you try unzip?

**Comment by yvonnebuschermoehle** [comment]
Tried it, that also works for me. But the tetgen.mexmaci64 file that I obtain with this method differs from the one I obtain when letting brainstorm download it automatically (see picture, the automatic download is on the left). 

![Bildschirmfoto 2020-05-16 um 18 47 44](https://user-images.githubusercontent.com/65216578/82125453-508cee00-97a6-11ea-8441-8e88f2d6616b.png)

**Comment by fangq** [comment]
@ftadel how does brainstorm unzip/install a package? if it does not support links, can you modify it to manually create a link (`system('ln -s ')` or `unix('ln -s ...')`)? alternatively, you can set method to 'tetgen1.5' directly on a mac.

**Comment by ftadel** [comment]
I simply use the unzip command from Matlab, which I never realized could not handle symbolic links...
https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/process/functions/process_generate_fem.m#L1140
https://www.mathworks.com/help/matlab/ref/unzip.html

Enforcing the version through code has better controlled side effects than doing operations on the file system without being able to test them (I don't have access to a Mac), so I'd prefer the second method. This would also enforce reproducibility across operating systems. We realized with this link that on Windows, surf3mesh calls by default the tetgen 1.4 while on MacOS it is expected to call tetgen 1.5 (independently from the fact that the link is missing when I unzip it with Matlab :)

I could updatd the surf2mesh call by modifying this line : https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/process/functions/process_generate_fem.m#L377
Before:

>             [node,elem] = surf2mesh(newnode, newelem, min(newnode), max(newnode),...
>                 OPTIONS.KeepRatio, factor_bst .* OPTIONS.MaxVol, regions, []);

After: 

>             [node,elem] = surf2mesh(newnode, newelem, min(newnode), max(newnode),...
>                 OPTIONS.KeepRatio, factor_bst .* OPTIONS.MaxVol, regions, [], [], 'tetgen1.5');

However, when running Tetget1.5 instead, I'm running into another problem, which relates to the second issue Yvonne was reporting on the Brainstorm forum: **The labeling logic of the tissues is different**.

With Yvonne's example, surf2mesh produces a different list of tissues (elem(:,5)):
- Tetgen1.4: Labels 3,4,5 => Three tissues, as expected for 3 non-intersecting surfaces (in some cases, I found a label 0 for isolated elements, which I simply discarded)
- Tetgen1.5: Labels 1,2,3,4 => Why 4 tissues? What am I supposed to do with it? 

Base on what we observed with the previous version, we assumed that the order and number of  (non-zero) tissues would always match the surfaces in input.  Was that a wrong assumption? What would be the best way to know what is what in the output "elem" variable?

**Comment by fangq** [comment]
@ftadel, sorry for the delay. I just did some quick test, and so far, the labeling logic between 1.4 and 1.5 seems to be consistent as long as the seeds (`regions` input in `s2m/surf2mesh`) are well defined.

Here is a test script:
```
% create a 10-layer lattice
[node,face,centroids]=latticegrid([0 60],[0 60],0:10:60);

% mesh with tetgen 1.4 (only works on non-mac)
[no,el]=s2m(node,face,1,10,'tetgen',centroids);
figure
subplot(121);
plotmesh(no,el,'x>30')

% mesh with tetgen 1.5
[no2,el2]=s2m(node,face,1,10,'tetgen1.5',centroids);
subplot(122);
plotmesh(no2,el2,'x>30')
```

I was able to get consistent labels. see the below plot

![Screenshot_2020-06-04_16-49-55](https://user-images.githubusercontent.com/226913/83808904-8de8eb00-a683-11ea-993f-a548e68408d6.png)

the difference between the two version is when the `regions` input is missing - tetgen1.4 labels every compartment by 0, while tetgen 1.5 assigns a random label.

My suspicion is that the seeds in your test data may have some issues, for example, seeds 1 and 2 are both included in the same surface compartment; or the seeds are missing from one of the compartments. I can no longer find the test data, but will be happy to check if you can repost the data link.

**Comment by yvonnebuschermoehle** [comment]
@fangq I sent you the data link via email ;)

**Comment by ftadel** [comment]
@fangq 
This was indeed the issue, the function defining the seeds was not doing its job correctly.
I fixed it in Brainstorm here: https://github.com/brainstorm-tools/brainstorm3/commit/0c4b6527062b186e7c252fd1a83d166982ea40bb

Thanks for all your help!

**Comment by fangq** [comment]
terrific!
