### ISSUE TITLE
Recompile for Apple M1 Macs

### ISSUE THREAD

**Issue by aa202** [fangq/iso2mesh#52]
Hi Dr. Fang, I was wondering if you could guide me on how to recompile the binaries on a Mac using Terminal? Thank you so much!

**Comment by fangq** [comment]
sorry for not responding to this inquery for such a long time. To recompile iso2mesh meshing utilities, you will need to run make inside this folder

https://github.com/fangq/iso2mesh/tree/master/tools

please see this section in README

https://github.com/fangq/iso2mesh/blob/master/README.md#compiling-iso2mesh

I've only done this on Linux, but it should be possible on the Mac if you have installed all dependencies.
