### ISSUE TITLE
Issue when Installing Iso2mesh in cluster (remote computation resources)

### ISSUE THREAD

**Issue by ZhichaoWang970201** [fangq/iso2mesh#56]
[zwang945@login-phoenix-1 tools]$ make clean
rm -rf  built #../bin
for i in cgalmesh cgalsimp2 cgalsurf cork meshfix meshfix/contrib/JMeshLib/test tetgen; do make --no-print-directory -C $i clean; done
make[2]: *** No rule to make target `clean'.  Stop.
make[1]: *** [clean] Error 2
make[2]: *** No rule to make target `clean'.  Stop.
make[1]: *** [clean] Error 2
make[2]: *** No rule to make target `clean'.  Stop.
make[1]: *** [clean] Error 2
rm: cannot remove ‘bin/off2obj’: No such file or directory
make[1]: [clean] Error 1 (ignored)
rm: cannot remove ‘lib/libcork.a’: No such file or directory
make[1]: [clean] Error 1 (ignored)
rm: cannot remove ‘lib/libcorkdebug.a’: No such file or directory
make[1]: [clean] Error 1 (ignored)
rm -f -f *.o jmeshlib
/bin/rm *.o *.a tetgen *~
/bin/rm: cannot remove ‘*.o’: No such file or directory
/bin/rm: cannot remove ‘*.a’: No such file or directory
/bin/rm: cannot remove ‘tetgen’: No such file or directory
/bin/rm: cannot remove ‘*~’: No such file or directory
make[1]: *** [clean] Error 1
make: *** [clean] Error 2

**Comment by fangq** [comment]
it looks like you did not check out the submodules. please see

https://github.com/fangq/iso2mesh/tree/master/tools

the folders tetgen, meshfix, and cork are pointers to other git repositories (i.e. a submodule), if you just clone iso2mesh, those will be empty folders, you have to use `git clone --recursive ...` to download all submodule files.
