### ISSUE TITLE
Warning about shadowed core library

### ISSUE THREAD

**Issue by Totrock** [fangq/iso2mesh#57]
I am using Ubuntu 18.04 and GNU Octave, version 4.2.2.
When using addpath on the precompiled [iso2mesh](https://sourceforge.net/projects/iso2mesh/files/iso2mesh/1.9.6%20%28Lion%20Head%29/) or 
> pkg load iso2mesh

to load iso2mesh from the [PPA](https://launchpad.net/~fangq/+archive/ubuntu/ppa) I get the following warnings:

warning: function ../iso2mesh196linux/base64encode.m shadows a core library function
warning: called from
    mmclab_help_example at line 4 column 1
warning: function ../iso2mesh196linux/base64decode.m shadows a core library function
warning: called from
    mmclab_help_example at line 4 column 1

With Octave 5.2 or 6.3 on Ubuntu 20.04 I don't have these warnings, so this problem might have solved itself.

**Comment by fangq** [comment]
I tested this on my octave 4.2.2 on Ubuntu 18.04, I could not see the warning - see screenshot below. I believe `base64_encode` is a built-in function, but not `base64encode` or `base64decode`

![iso2mesh_base64encode](https://user-images.githubusercontent.com/226913/129393604-b255259b-8c05-4fb3-9b79-54019c389f02.png)

on the other hand, in the Debian package I created, the `base64{encode,decode}` functions were removed from the package to avoid conflict with `octave-jsonlab`, see

https://salsa.debian.org/pkg-octave-team/octave-iso2mesh/-/blob/debian/latest/debian/rules#L22

again, it is possible that my ppa version of the iso2mesh package was too old. I do think that octave 5.2/6 do not have such issue suggest that it is a local problem.

can you run `locate base64encode.m` and find out which file is in conflict?

**Comment by Totrock** [comment]
Sorry about that one. This one was the issue:
/usr/share/psychtoolbox-3/PsychHardware/iViewXToolbox/cbase64/base64encode.m
... because i did a lazy `sudo apt install octave-*` which includes `octave-psychtoolbox-3`
I don't need this package anyway, so I removed it and the warning is now gone.

**Comment by fangq** [comment]
thanks for the update. I am closing this ticket for now.
