### ISSUE TITLE
cgalsimp2 command failed

### ISSUE THREAD

**Issue by zhiweigong75** [fangq/iso2mesh#64]
Hi @fangq 

I faced an issue using the **_meshresample.m_** with my Mac M1 chip (macOS Monterey 12.4).

Here is the error:

<img width="750" alt="Screen Shot 2022-07-10 at 11 19 32 PM" src="https://user-images.githubusercontent.com/90117778/178182403-39ee954f-f34c-4250-a54f-8a964a11d2a3.png">

**Comment by fangq** [comment]
@zhiweigong75, unfortunately iso2mesh does not include any pre-compiled binaries for M1 processors. I expect that not only meshresample.m does not work, many other functions such as meshcheckrepair and s2m/surf2mesh also won't work.

you can, however, compile it yourself if you can set up the building environment. To compile these binaries, you need to run `make` inside the `iso2mesh/tools` folder

https://github.com/fangq/iso2mesh/tree/master/tools

you should also use `git submodule update --init --remote` to download all submodules under that folder. I anticipate setting up the compilation enviroment will take some time. currently, the included Makefile only works on Ubuntu Linux.

**Comment by mikami520** [comment]
> @zhiweigong75, unfortunately iso2mesh does not include any pre-compiled binaries for M1 processors. I expect that not only meshresample.m does not work, many other functions such as meshcheckrepair and s2m/surf2mesh also won't work.
> 
> you can, however, compile it yourself if you can set up the building environment. To compile these binaries, you need to run `make` inside the `iso2mesh/tools` folder
> 
> https://github.com/fangq/iso2mesh/tree/master/tools
> 
> you should also use `git submodule update --init --remote` to download all submodules under that folder. I anticipate setting up the compilation enviroment will take some time. currently, the included Makefile only works on Ubuntu Linux.

@fangq Hi, I am the teammate of @zhiweigong75. I tried two ways to use ```iso2mesh```. 
1. I installed ```iso2mesh``` by ```MATLAB Add-Ons```, when I called ```vol2surf```, the MATLAB quit without reasons by just killing the process. Here is the error message:
```
sakuraxiao@ubuntu:~/Desktop/Statistical-Shape-Modeling/asm-master$ matlab
MATLAB is selecting SOFTWARE OPENGL rendering.
Killed
```

2. I followed the instruction to compile ```iso2mesh```. when I called ```make clean```, it gave me some errors and I had no idea to solve them. Here is the error message:
```
sakuraxiao@ubuntu:~/Desktop/iso2mesh/tools$ make clean
rm -rf  built #../bin
for i in cgalmesh cgalsimp2 cgalsurf cork meshfix meshfix/contrib/JMeshLib/test tetgen; do make --no-print-directory -C $i clean; done
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: *** No rule to make target 'clean'.  Stop.
rm: cannot remove 'bin/off2obj': No such file or directory
Makefile:245: recipe for target 'clean' failed
make[1]: [clean] Error 1 (ignored)
rm: cannot remove 'lib/libcork.a': No such file or directory
Makefile:245: recipe for target 'clean' failed
make[1]: [clean] Error 1 (ignored)
rm: cannot remove 'lib/libcorkdebug.a': No such file or directory
Makefile:245: recipe for target 'clean' failed
make[1]: [clean] Error 1 (ignored)
make[1]: *** No rule to make target 'clean'.  Stop.
rm -f -f *.o jmeshlib
/bin/rm *.o *.a tetgen *~
/bin/rm: cannot remove '*.o': No such file or directory
/bin/rm: cannot remove '*.a': No such file or directory
/bin/rm: cannot remove 'tetgen': No such file or directory
/bin/rm: cannot remove '*~': No such file or directory
makefile:58: recipe for target 'clean' failed
make[1]: *** [clean] Error 1
commons/Makefile_common.mk:108: recipe for target 'clean' failed
make: *** [clean] Error 2
```
### Do you have any ideas about these two installation methods? Thank you in advance!
