### ISSUE TITLE
problem in installing and running iso2mesh in MATLAB

### ISSUE THREAD

**Issue by 1191620** [fangq/iso2mesh#66]
Hello 
I'm able to download toolbox from my account on Mathsworks, but I can't seem to install it ; there is no installer in the package download.
![image](https://user-images.githubusercontent.com/107300580/180368109-a9d206f3-a178-4c67-af29-7c932e8ebecd.png)

Is it a problem related to my matlab version or another thing exist.
not that: I am using MATLAB R2016B AND for other toolboxes things is as same as iso2mesh .
Thanks a lot .

**Comment by fangq** [comment]
@1191620, iso2mesh does not have a MATLAB installer. you just download it, unzip the folder, and add path in matlab, see the installation instruction in this document

https://github.com/fangq/iso2mesh/blob/master/doc/INSTALL.txt
