### ISSUE TITLE
jmeshlib command failed: ERROR- Can't open file.

### ISSUE THREAD

**Issue by HHHit** [fangq/iso2mesh#67]
I was trying to run a mesh repair fix for many meshes, and I am hoping to run in parallel. However, it reports
`jmeshlib command failed:
ERROR- Can't open file.`

**Comment by fangq** [comment]
@HHHit, iso2mesh uses a default temporary folder to write intermediate files, you can get this folder name by typing `mwpath`.

when you run multiple jobs, to avoid each job overwriting each other's outputs, you need to set a variable `ISO2MESH_SESSION` in the MATLAB base workspace to add a unique prefix to each output file; alternatively, you can also define different temporary folder name by using the `ISO2MESH_TEMP` variable.

Please see this wiki page for details

https://iso2mesh.sourceforge.net/cgi-bin/index.cgi?Advanced

if this does not solve the problem, feel free to re-open the issue.
