### ISSUE TITLE
cgalsimp2 for ARM64 is not compiled/added to bin directory

### ISSUE THREAD

**Issue by andy-s-ding** [fangq/iso2mesh#80]
Running vol2surf with method "simplify" on an ARM64 Mac throws an error that cgalsimp2.mexmaca64 is missing in the bin directory. I do not see this file in the latest push either. Could we please have this module recompiled for ARM64 compatibility? Thank you!

**Comment by fangq** [comment]
thanks for reporting this - I have just added the missing `cgalsimp2.mexmaca64` binary. let me know if this works for you.
